name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Läuft jeden Tag um Mitternacht
  workflow_dispatch: # Ermöglicht manuelles Ausführen im Actions-Tab

# WICHTIG: Erlaubt dem Workflow, den Output-Branch zu erstellen und zu beschreiben
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: aimen056
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
